repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
      - id: double-quote-string-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args:
          - "--autofix"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
